import { useMemo, useState, type ReactNode, type Dispatch, type SetStateAction, type FormEvent } from 'react';
import { Heart, Search, ShoppingBag, UserRound, Menu, X, Minus, Plus, ArrowRight, Check, Package, ShieldCheck, RotateCcw, SlidersHorizontal, LayoutDashboard } from 'lucide-react';
import { Link, Route, Switch, useLocation, useParams } from 'wouter';

type Category = 'women' | 'men' | 'girls' | 'boys' | 'kids';
type Product = { id: string; name: string; category: Category; type: string; price: number; oldPrice?: number; image: string; alt: string; badge?: string; colors: string[]; description: string };
type CartItem = { product: Product; size: string; qty: number };

const img = (id: string) => `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&w=900`;
const products: Product[] = [
  { id:'saffron-drape', name:'Saffron Drape Dress', category:'women', type:'Dresses', price:2890, oldPrice:3490, image:img('985635'), alt:'Woman in a flowing saffron dress', badge:'Bestseller', colors:['Saffron','Ink'], description:'A fluid, easy silhouette cut for movement. Made in a soft cotton-satin blend with a softly gathered waist.' },
  { id:'indigo-kurta', name:'Indigo Handloom Kurta', category:'men', type:'Kurtas', price:2190, image:img('1043474'), alt:'Man wearing a blue kurta', colors:['Indigo','Ivory'], description:'A relaxed everyday kurta with a crisp band collar and hand-finished details.' },
  { id:'rose-coord', name:'Rosewood Co-ord Set', category:'girls', type:'Sets', price:1790, oldPrice:2290, image:img('1620760'), alt:'Girl in a rose colored outfit', badge:'New in', colors:['Rosewood','Peach'], description:'A two-piece set for big days and little adventures. Light, joyful and made to last.' },
  { id:'sage-shirt', name:'Sage Camp Shirt', category:'boys', type:'Shirts', price:1290, image:img('167404'), alt:'Boy in a casual sage shirt', colors:['Sage','Cloud'], description:'Sun-ready cotton with an easy camp collar and generous pockets.' },
  { id:'cloud-set', name:'Cloud Cotton Set', category:'kids', type:'Loungewear', price:990, image:img('3662847'), alt:'Child in comfortable cotton clothing', colors:['Cloud','Oat'], description:'The softest little uniform for slow mornings and long afternoons.' },
  { id:'terracotta-sari', name:'Terracotta Silk Saree', category:'women', type:'Sarees', price:6790, image:img('1926769'), alt:'Woman in elegant terracotta sari', badge:"Editor's pick", colors:['Terracotta','Marigold'], description:'A modern heirloom: luminous silk, a tonal border, and just enough drama.' },
  { id:'stone-overshirt', name:'Stone Linen Overshirt', category:'men', type:'Jackets', price:2490, image:img('1043471'), alt:'Man in a linen overshirt', colors:['Stone','Olive'], description:'A breathable layer with a workwear soul. Wear open over everything.' },
  { id:'cobalt-frock', name:'Cobalt Party Frock', category:'girls', type:'Dresses', price:1590, image:img('1516680'), alt:'Girl in a cobalt dress', colors:['Cobalt','Lily'], description:'A twirl-friendly frock with a neat bow and a little bit of occasion.' },
  { id:'rust-tee', name:'Rust Club Tee', category:'boys', type:'T-Shirts', price:790, oldPrice:990, image:img('1624496'), alt:'Boy in a rust t-shirt', colors:['Rust','Ink'], description:'A heavyweight jersey tee with a graphic inspired by India’s old matchbooks.' },
  { id:'marigold-romper', name:'Marigold Day Romper', category:'kids', type:'Sets', price:1190, image:img('1620653'), alt:'Child in a sunny marigold romper', colors:['Marigold','Cream'], description:'An easy one-piece with cheerful colour and clever snap closures.' },
  { id:'black-edit-blazer', name:'The Edit Blazer', category:'women', type:'Jackets', price:4290, image:img('994523'), alt:'Woman in a tailored black blazer', colors:['Ink','Mushroom'], description:'Sharp shoulders, soft tailoring. The one that makes every outfit feel considered.' },
  { id:'olive-trouser', name:'Olive Pleat Trouser', category:'men', type:'Trousers', price:1990, image:img('1043473'), alt:'Man wearing olive trousers', colors:['Olive','Charcoal'], description:'A generous pleat and a clean break, cut in a brushed cotton twill.' },
  { id:'lotus-wrap-top', name:'Lotus Wrap Top', category:'women', type:'Tops', price:1690, image:img('1488463'), alt:'Woman wearing a light wrap top', badge:'New in', colors:['Lotus','Ink'], description:'A soft wrap front and easy three-quarter sleeves make this the quiet hero of your wardrobe.' },
  { id:'mango-midi-skirt', name:'Mango Midi Skirt', category:'women', type:'Skirts', price:2290, oldPrice:2690, image:img('1644888'), alt:'Woman in a warm yellow midi skirt', colors:['Mango','Cocoa'], description:'A sunlit midi with a fluid fall, designed to move from first coffee to last dance.' },
  { id:'ivory-embroidered-kurta', name:'Ivory Embroidered Kurta', category:'women', type:'Kurtas', price:3190, image:img('1486974'), alt:'Woman in an ivory embroidered kurta', badge:'Hand finished', colors:['Ivory','Rose'], description:'Fine tonal embroidery traces the neckline of this breathable cotton kurta.' },
  { id:'plum-cowl-top', name:'Plum Cowl Top', category:'women', type:'Tops', price:1890, image:img('1619488'), alt:'Woman wearing a plum colored top', colors:['Plum','Sand'], description:'A considered drape, a clean hem and a colour that does the talking after dark.' },
  { id:'pearl-cotton-saree', name:'Pearl Cotton Saree', category:'women', type:'Sarees', price:3890, image:img('1536619'), alt:'Woman wearing a pale cotton saree', badge:"Editor's pick", colors:['Pearl','Cinnamon'], description:'Lightweight cotton with a narrow contrast border, made for long lunches and longer evenings.' },
  { id:'maroon-bandhgala', name:'Maroon Bandhgala Jacket', category:'men', type:'Jackets', price:3590, image:img('1043472'), alt:'Man in a maroon bandhgala jacket', badge:'New in', colors:['Maroon','Sand'], description:'A sharp band collar and a softly structured shoulder give this festive layer its quiet confidence.' },
  { id:'cream-knit-polo', name:'Cream Knit Polo', category:'men', type:'Shirts', price:1790, oldPrice:2190, image:img('1681010'), alt:'Man in a cream knitted polo shirt', colors:['Cream','Moss'], description:'A textured knit polo with a relaxed fit for warm days, cool evenings and everything between.' },
  { id:'charcoal-city-shirt', name:'Charcoal City Shirt', category:'men', type:'Shirts', price:1590, image:img('769733'), alt:'Man wearing a charcoal shirt', colors:['Charcoal','White'], description:'A crisp shirt with a roomy cut and a softened finish that feels right all day.' },
  { id:'sand-cargo-pant', name:'Sand Utility Pant', category:'men', type:'Trousers', price:2090, image:img('1183266'), alt:'Man wearing sand colored trousers', colors:['Sand','Ink'], description:'Practical pockets, a clean tapered leg and a sturdy cotton weave for wherever the day goes.' },
  { id:'ink-oversized-tee', name:'Ink Oversized Tee', category:'men', type:'T-Shirts', price:890, image:img('8532616'), alt:'Man in an oversized black t-shirt', colors:['Ink','Chalk'], description:'The everyday essential, cut generously in heavyweight jersey with a considered neckline.' },
  { id:'lilac-tiered-dress', name:'Lilac Tiered Dress', category:'girls', type:'Dresses', price:1890, image:img('1520760'), alt:'Girl wearing a lilac tiered dress', badge:'New in', colors:['Lilac','Cloud'], description:'Three easy tiers and a little volume make this a favourite for twirls, birthdays and beyond.' },
  { id:'indigo-denim-dungaree', name:'Indigo Denim Dungaree', category:'girls', type:'Sets', price:2190, image:img('1620761'), alt:'Girl wearing an indigo denim dungaree', colors:['Indigo','Poppy'], description:'A soft denim dungaree with adjustable straps and plenty of room for growing.' },
  { id:'poppy-party-skirt', name:'Poppy Party Skirt', category:'girls', type:'Skirts', price:1390, oldPrice:1690, image:img('1620819'), alt:'Girl wearing a bright poppy skirt', colors:['Poppy','Blush'], description:'A joyful pop of colour with a comfortable elastic waist and a full, swishy shape.' },
  { id:'petal-embroidered-kurta', name:'Petal Embroidered Kurta', category:'girls', type:'Kurtas', price:1590, image:img('1620653'), alt:'Girl in a pastel embroidered kurta', badge:'Festive edit', colors:['Petal','Marigold'], description:'Tiny floral stitches and a breezy cotton weave make this one ready for every family gathering.' },
  { id:'bluebell-jumpsuit', name:'Bluebell Jumpsuit', category:'girls', type:'Sets', price:1790, image:img('1648353'), alt:'Girl wearing a blue jumpsuit', colors:['Bluebell','Ivory'], description:'A one-and-done outfit with a gentle square neck and a waist made for comfortable adventures.' },
  { id:'mustard-check-shirt', name:'Mustard Check Shirt', category:'boys', type:'Shirts', price:1190, image:img('1624076'), alt:'Boy wearing a mustard checked shirt', badge:'Bestseller', colors:['Mustard','Ink'], description:'A cheerful brushed cotton check with a classic collar and a little extra room to roam.' },
  { id:'denim-drawstring-short', name:'Denim Drawstring Short', category:'boys', type:'Trousers', price:990, image:img('1625478'), alt:'Boy wearing denim shorts', colors:['Denim','Oat'], description:'A soft, washed denim short with an easy drawstring waist and deep pockets.' },
  { id:'forest-hoodie', name:'Forest Zip Hoodie', category:'boys', type:'Jackets', price:1490, oldPrice:1790, image:img('1627123'), alt:'Boy wearing a forest green hoodie', colors:['Forest','Oat'], description:'A light layer for early starts and late play, finished with a roomy hood and smooth zip.' },
  { id:'cherry-graphic-tee', name:'Cherry Graphic Tee', category:'boys', type:'T-Shirts', price:790, image:img('1624496'), alt:'Boy wearing a cherry red graphic t-shirt', badge:'Under ₹999', colors:['Cherry','Cloud'], description:'A bright everyday tee with a small hand-drawn graphic and soft cotton jersey.' },
  { id:'sky-blue-kurta', name:'Sky Blue Kurta Set', category:'boys', type:'Kurtas', price:1990, image:img('1624076'), alt:'Boy wearing a sky blue kurta set', badge:'Festive edit', colors:['Sky','Ivory'], description:'A clean, comfortable kurta set for celebrations that last all afternoon.' },
  { id:'oat-ribbed-romper', name:'Oat Ribbed Romper', category:'kids', type:'Loungewear', price:890, image:img('3662830'), alt:'Small child in a ribbed oat romper', badge:'Under ₹999', colors:['Oat','Sage'], description:'A soft ribbed one-piece with easy snaps and a gentle fit for tiny everyday explorers.' },
  { id:'coral-sun-dress', name:'Coral Sun Dress', category:'kids', type:'Dresses', price:1290, image:img('3662667'), alt:'Child wearing a coral summer dress', colors:['Coral','Lemon'], description:'A bright little dress in airy cotton, with a generous skirt made for sunny afternoons.' },
  { id:'meadow-overall-set', name:'Meadow Overall Set', category:'kids', type:'Sets', price:1490, image:img('3661358'), alt:'Child wearing a meadow colored overall set', colors:['Meadow','Cream'], description:'A playful overall layered over a soft tee, made for crawling, climbing and curious days.' },
  { id:'navy-stripe-pyjama', name:'Navy Stripe Pyjama Set', category:'kids', type:'Loungewear', price:1090, oldPrice:1290, image:img('3662883'), alt:'Child wearing navy striped pyjamas', colors:['Navy','Cloud'], description:'A breathable bedtime set with a tiny stripe and a relaxed fit for better dreams.' },
  { id:'lemon-sweatshirt', name:'Lemon Everyday Sweatshirt', category:'kids', type:'T-Shirts', price:990, image:img('3662847'), alt:'Child wearing a lemon yellow sweatshirt', badge:'Bestseller', colors:['Lemon','Oat'], description:'A soft loopback sweatshirt in a happy shade, finished with neat ribbed cuffs.' },
];
const categories: { key:Category; label:string; image:string }[] = [
  {key:'women',label:'Women',image:img('985635')},{key:'men',label:'Men',image:img('1043474')},{key:'girls',label:'Girls',image:img('1620760')},{key:'boys',label:'Boys',image:img('167404')},{key:'kids',label:'Kids',image:img('3662847')},
];
const money = (n:number) => `₹${n.toLocaleString('en-IN')}`;

function Shell({ children, cartCount, wishCount, search, setSearch }: { children:ReactNode; cartCount:number; wishCount:number; search:string; setSearch:(v:string)=>void }) {
  const [menu,setMenu] = useState(false); const [location] = useLocation();
  return <div className="page">
    <div className="announce" data-testid="text-announcement">FREE SHIPPING ON ORDERS ABOVE ₹999&nbsp; | &nbsp;EASY 7-DAY RETURNS</div>
    <header className="nav">
      <button className="icon-btn mobile-toggle" onClick={()=>setMenu(!menu)} data-testid="button-mobile-menu">{menu?<X size={19}/>:<Menu size={19}/>}</button>
      <Link href="/" className="logo" data-testid="link-home">style<span>h</span><i>u</i>b</Link>
      <nav className={`navlinks ${menu?'open':''}`}>
        {categories.map(c=><Link key={c.key} href={`/category/${c.key}`} className={location.includes(c.key)?'active':''} data-testid={`link-category-${c.key}`}>{c.label}</Link>)}
        <Link href="/admin" className={location==='/admin'?'active':''} data-testid="link-admin">Studio</Link>
      </nav>
      <div className="nav-actions">
        <div className="search-wrap"><Search size={15}/><input aria-label="Search products" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search the edit" data-testid="input-search"/></div>
        <Link className="icon-btn" href="/wishlist" data-testid="link-wishlist"><Heart size={18}/>{wishCount>0&&<span className="count">{wishCount}</span>}</Link>
        <Link className="icon-btn" href="/account" data-testid="link-account"><UserRound size={18}/></Link>
        <Link className="icon-btn" href="/cart" data-testid="link-cart"><ShoppingBag size={18}/>{cartCount>0&&<span className="count">{cartCount}</span>}</Link>
      </div>
    </header>
    {menu&&<div className="mobile-menu">{categories.map(c=><Link key={c.key} href={`/category/${c.key}`} onClick={()=>setMenu(false)} data-testid={`mobile-link-${c.key}`}>{c.label}</Link>)}</div>}
    {children}
  </div>;
}

function ProductCard({ product, saved, toggleWish, addCart, index=0 }: { product:Product; saved:boolean; toggleWish:(p:Product)=>void; addCart:(p:Product)=>void; index?:number }) {
  return <article className="product-card" style={{animationDelay:`${index*45}ms`}} data-testid={`card-product-${product.id}`}>
    <div className="product-image">
      {product.badge&&<span className="badge">{product.badge}</span>}<Link href={`/product/${product.id}`} data-testid={`link-product-${product.id}`}><img src={product.image} alt={product.alt}/></Link><button className={`save-btn ${saved?'saved':''}`} onClick={()=>toggleWish(product)} aria-label={`Save ${product.name}`} data-testid={`button-save-${product.id}`}><Heart size={16} fill={saved?'currentColor':'none'}/></button>
    </div>
    <div className="product-info"><h3>{product.name}</h3><p>{product.type} · {product.colors[0]}</p><span className="price">{money(product.price)}{product.oldPrice&&<span className="old-price">{money(product.oldPrice)}</span>}</span><button className="text-link" style={{display:'block',marginTop:10,border:0,background:'none',padding:0}} onClick={()=>addCart(product)} data-testid={`button-add-${product.id}`}>Quick add <ArrowRight size={12} style={{verticalAlign:'middle'}}/></button></div>
  </article>;
}

function Home({ wish, toggleWish, addCart }: { wish:Product[]; toggleWish:(p:Product)=>void; addCart:(p:Product)=>void }) {
  return <main>
    <section className="hero"><div className="hero-copy"><span className="eyebrow">The new season / Chapter 01</span><h1>Style That <em>Defines</em> You</h1><p>Discover the latest fashion for everyone in the family.</p><Link href="/category/women" className="btn btn-dark" data-testid="link-shop-women">Shop the new edit <ArrowRight size={15}/></Link></div><div className="hero-media"><span className="hero-tag">A story in every stitch</span></div></section>
    <div className="ticker"><span>NEW SEASON / NEW ENERGY</span><span>MADE FOR REAL LIFE</span><span>STYLEHUB SELECTS</span><span>NEW SEASON / NEW ENERGY</span></div>
    <section className="section container"><div className="section-head"><div><span className="eyebrow">Shop by mood</span><h2>Something for everyone</h2></div><Link className="text-link" href="/category/women" data-testid="link-view-all">View all pieces <ArrowRight size={12} style={{verticalAlign:'middle'}}/></Link></div><div className="category-strip">{categories.map(c=><Link key={c.key} className="category-card" style={{backgroundImage:`url(${c.image})`}} href={`/category/${c.key}`} data-testid={`card-category-${c.key}`}><span>{c.label}</span></Link>)}</div></section>
    <section className="section" style={{background:'hsl(var(--muted))'}}><div className="container"><div className="section-head"><div><span className="eyebrow">The considered edit</span><h2>Pieces with a point of view</h2></div></div><div className="product-grid">{products.slice(0,4).map((p,i)=><ProductCard key={p.id} product={p} index={i} saved={wish.some(x=>x.id===p.id)} toggleWish={toggleWish} addCart={addCart}/>)}</div></div></section>
    <section className="section container"><div className="editorial"><div className="editorial-main"><div className="editorial-copy"><span className="eyebrow" style={{color:'#ead6c6'}}>Journal / 01</span><h3>Colour outside the lines.</h3><p>A little more joy in the everyday. Our take on occasion dressing is bright, effortless and made for the people you actually want to see.</p><Link href="/category/girls" className="btn btn-light" data-testid="link-read-colour">Explore occasion</Link></div></div><div className="editorial-side"><div className="editorial-copy"><span className="eyebrow" style={{color:'#ead6c6'}}>For the ones who roam</span><h3>Soft power, daily.</h3><Link href="/category/men" className="btn btn-light" data-testid="link-explore-men">See men's edit</Link></div></div></div></section>
    <section className="marquee-band"><span className="eyebrow">StyleHub journal</span><h2>Wear your own weather.</h2></section>
    <section className="quote"><span className="eyebrow" style={{color:'#d7bdae'}}>A note from StyleHub</span><blockquote>“The best dressed families are not matching. They are in conversation.”</blockquote><cite>— Our studio, New Delhi</cite></section>
    <Newsletter/>
  </main>;
}
function Newsletter(){ const [email,setEmail]=useState(''); const [done,setDone]=useState(false); return <section className="newsletter"><div><span className="eyebrow">A good note, occasionally</span><h2>Come for the clothes.<br/><em>Stay for the feeling.</em></h2><p>First look at new drops, quiet offers and stories from the StyleHub studio.</p>{done?<p style={{fontWeight:700}}>You're on the list. See you soon.</p>:<form className="newsletter-form" onSubmit={e=>{e.preventDefault();if(email)setDone(true)}}><input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="Your email address" required data-testid="input-newsletter"/><button data-testid="button-newsletter">Sign me up <ArrowRight size={13}/></button></form>}</div></section>; }

function Catalog({ category, wish, toggleWish, addCart, search }: { category:Category; wish:Product[]; toggleWish:(p:Product)=>void; addCart:(p:Product)=>void; search:string }) {
  const [filter,setFilter]=useState('All'); const [sort,setSort]=useState('featured');
  const label=categories.find(c=>c.key===category)?.label||'Edit'; const types=['All',...Array.from(new Set(products.filter(p=>p.category===category).map(p=>p.type)))];
  const shown=useMemo(()=>products.filter(p=>p.category===category).filter(p=>(filter==='All'||p.type===filter)&&p.name.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>sort==='price-low'?a.price-b.price:sort==='price-high'?b.price-a.price:0),[category,filter,sort,search]);
  return <main><div className="catalog-head"><div className="container"><span className="eyebrow">The collection / 0{categories.findIndex(c=>c.key===category)+1}</span><h1>{label}</h1><p>Thoughtful shapes, expressive colour and everyday pieces that make room for your life.</p></div></div><section className="container"><div className="catalog-controls"><div className="filters">{types.map(t=><button key={t} className={`pill ${filter===t?'active':''}`} onClick={()=>setFilter(t)} data-testid={`button-filter-${t.toLowerCase()}`}>{t}</button>)}</div><select className="sort" value={sort} onChange={e=>setSort(e.target.value)} aria-label="Sort products" data-testid="select-sort"><option value="featured">Sort: Featured</option><option value="price-low">Price: Low to high</option><option value="price-high">Price: High to low</option></select></div>{shown.length?<div className="product-grid" style={{paddingBottom:100}}>{shown.map((p,i)=><ProductCard key={p.id} product={p} index={i} saved={wish.some(x=>x.id===p.id)} toggleWish={toggleWish} addCart={addCart}/>)}</div>:<div className="empty"><SlidersHorizontal size={23}/><h2>No pieces here yet.</h2><p>Try a different filter or search term.</p></div>}</section></main>;
}

function ProductDetail({ wish, toggleWish, addCart }: { wish:Product[]; toggleWish:(p:Product)=>void; addCart:(p:Product,s?:string)=>void }) {
  const {id}=useParams<{id:string}>(); const p=products.find(x=>x.id===id)||products[0]; const [size,setSize]=useState('M'); const [image,setImage]=useState(p.image); const saved=wish.some(x=>x.id===p.id);
  return <main className="container detail"><div><div className="detail-image"><img src={image} alt={p.alt}/></div><div className="thumbs"><img className="active" src={p.image} onClick={()=>setImage(p.image)} alt="Front view" data-testid="button-image-front"/><img src={p.image} style={{objectPosition:'70% center'}} onClick={()=>setImage(p.image)} alt="Detail view" data-testid="button-image-detail"/></div></div><div><span className="eyebrow">{p.category} / {p.type}</span><h1>{p.name}</h1><div className="detail-price">{money(p.price)} {p.oldPrice&&<span className="old-price">{money(p.oldPrice)}</span>}</div><p className="detail-copy">{p.description} Designed in our Delhi studio and made with partners we know by name.</p><label className="selector-label">Select size</label><div className="size-row">{['XS','S','M','L','XL'].map(s=><button key={s} className={`size ${size===s?'selected':''}`} onClick={()=>setSize(s)} data-testid={`button-size-${s}`}>{s}</button>)}</div><div className="add-row"><button className="btn btn-dark" onClick={()=>addCart(p,size)} data-testid="button-add-to-bag">Add to bag <ShoppingBag size={15}/></button><button className={`btn ${saved?'btn-dark':'btn-light'}`} onClick={()=>toggleWish(p)} data-testid="button-detail-wishlist"><Heart size={15} fill={saved?'currentColor':'none'}/>{saved?'Saved':'Save'}</button></div><div className="benefits"><div className="benefit"><Package size={17}/><span><b>Free delivery</b><br/>On orders above ₹999</span></div><div className="benefit"><RotateCcw size={17}/><span><b>Easy returns</b><br/>7 days, no questions asked</span></div><div className="benefit"><ShieldCheck size={17}/><span><b>Made to be kept</b><br/>Quality checked before it leaves us</span></div></div></div></main>;
}

function Cart({cart,setCart}:{cart:CartItem[];setCart:Dispatch<SetStateAction<CartItem[]>>}) {
  const subtotal=cart.reduce((a,x)=>a+x.product.price*x.qty,0); const shipping=subtotal>=999||subtotal===0?0:99;
  const change=(id:string,d:number)=>setCart(c=>c.map(x=>x.product.id===id?{...x,qty:Math.max(1,x.qty+d)}:x));
  return <main className="container cart-layout"><div><span className="eyebrow">Your edit</span><h1 className="page-title">Shopping bag</h1>{cart.length?cart.map(x=><div className="cart-item" key={`${x.product.id}-${x.size}`}><img src={x.product.image} alt={x.product.alt}/><div><h3>{x.product.name}</h3><p>Size {x.size} · {x.product.colors[0]}</p><div className="qty"><button onClick={()=>change(x.product.id,-1)} data-testid={`button-decrease-${x.product.id}`}><Minus size={13}/></button><span data-testid={`text-quantity-${x.product.id}`}>{x.qty}</span><button onClick={()=>change(x.product.id,1)} data-testid={`button-increase-${x.product.id}`}><Plus size={13}/></button></div><br/><button className="cart-remove" onClick={()=>setCart(c=>c.filter(i=>i.product.id!==x.product.id))} data-testid={`button-remove-${x.product.id}`}>Remove</button></div><strong>{money(x.product.price*x.qty)}</strong></div>):<div className="empty"><ShoppingBag size={24}/><h2>Your bag is waiting.</h2><p>Beautiful things belong in the real world.</p><Link className="btn btn-dark" href="/" data-testid="link-continue-shopping">Start exploring</Link></div>}</div>{cart.length>0&&<aside className="summary"><h2>Order summary</h2><div className="summary-line"><span>Subtotal</span><b>{money(subtotal)}</b></div><div className="summary-line"><span>Shipping</span><b>{shipping===0?'Free':money(shipping)}</b></div><div className="summary-line summary-total"><span>Total</span><b>{money(subtotal+shipping)}</b></div><Link className="btn btn-dark" href="/checkout" data-testid="link-checkout">Continue to checkout <ArrowRight size={14}/></Link><p style={{fontSize:10,color:'hsl(var(--muted-foreground))',textAlign:'center'}}>Taxes included. Secure checkout.</p></aside>}</main>;
}

function Checkout({cart,onOrder}:{cart:CartItem[];onOrder:()=>void}){ const [done,setDone]=useState(false); const submit=(e:FormEvent)=>{e.preventDefault();setDone(true);onOrder()}; if(done)return <OrderConfirmation/>; return <main className="container form-page"><div className="checkout-layout"><form onSubmit={submit}><span className="eyebrow">Almost yours</span><h1 className="page-title">Checkout</h1><div className="form-grid"><div className="field"><label>First name</label><input required placeholder="Aarav" data-testid="input-first-name"/></div><div className="field"><label>Last name</label><input required placeholder="Mehta" data-testid="input-last-name"/></div><div className="field full"><label>Address</label><input required placeholder="Flat, street, neighbourhood" data-testid="input-address"/></div><div className="field"><label>City</label><input required placeholder="Mumbai" data-testid="input-city"/></div><div className="field"><label>PIN code</label><input required pattern="[0-9]{6}" placeholder="400001" data-testid="input-pincode"/></div><div className="field full"><label>Payment</label><select data-testid="select-payment"><option>Cash on delivery</option><option>UPI (demo)</option><option>Card (demo)</option></select></div></div><button className="btn btn-dark" style={{marginTop:28}} data-testid="button-place-order">Place order <ArrowRight size={14}/></button></form><aside className="summary"><h2>Your pieces</h2>{cart.map(x=><div className="summary-line" key={x.product.id}><span>{x.product.name} × {x.qty}</span><b>{money(x.product.price*x.qty)}</b></div>)}</aside></div></main> }
function OrderConfirmation(){return <main className="order-success"><div className="success-mark"><Check size={28}/></div><span className="eyebrow">Order confirmed / SH-24081</span><h1>It’s on its way to you.</h1><p>Thanks for shopping the StyleHub edit. We’ll send updates to your inbox as your pieces move from our studio to your door.</p><div className="track">{['Placed','Packed','On the way','Delivered'].map((s,i)=><div className={`track-step ${i<2?'done':''}`} key={s}><i>{i<2?<Check size={12}/>:i+1}</i><span>{s}</span></div>)}</div><Link className="btn btn-dark" href="/account" data-testid="link-track-order">Track my order <ArrowRight size={14}/></Link></main>}
function Wishlist({wish,toggleWish,addCart}:{wish:Product[];toggleWish:(p:Product)=>void;addCart:(p:Product)=>void}){return <main className="container" style={{padding:'60px 0 100px'}}><span className="eyebrow">Saved for later</span><h1 className="page-title">Your wishlist</h1>{wish.length?<div className="product-grid">{wish.map((p,i)=><ProductCard key={p.id} product={p} index={i} saved toggleWish={toggleWish} addCart={addCart}/>)}</div>:<div className="empty"><Heart size={24}/><h2>A shortlist in the making.</h2><p>Tap the heart on anything that feels like you.</p><Link className="btn btn-dark" href="/" data-testid="link-wishlist-explore">Explore the edit</Link></div>}</main>}
function Account(){return <main className="container account-grid"><div className="account-nav"><button className="active" data-testid="button-account-overview">Overview</button><button data-testid="button-account-orders">Orders</button><button data-testid="button-account-details">Details</button></div><div><span className="eyebrow">Namaste, Aanya</span><h1 className="page-title">Your account</h1><div className="summary" style={{position:'static',maxWidth:600}}><span className="eyebrow">Latest order</span><h2>Order SH-24081</h2><p style={{fontSize:12,color:'hsl(var(--muted-foreground))'}}>Placed 18 June 2025 · 2 items</p><div className="track"><div className="track-step done"><i><Check size={12}/></i><span>Placed</span></div><div className="track-step done"><i><Check size={12}/></i><span>Packed</span></div><div className="track-step done"><i><Package size={12}/></i><span>On the way</span></div><div className="track-step"><i>4</i><span>Delivered</span></div></div><Link className="btn btn-dark" href="/category/women" data-testid="link-account-shop">Keep shopping <ArrowRight size={14}/></Link></div></div></main>}
function Admin(){return <main className="container admin"><div className="admin-top"><div><span className="eyebrow">StyleHub studio / private view</span><h1 className="page-title">The back room.</h1></div><button className="btn btn-dark" onClick={()=>alert('Product editor opened in demo mode')} data-testid="button-admin-add-product"><Plus size={14}/> Add product</button></div><div className="admin-grid"><div className="metric"><small>Gross sales / June</small><strong>₹4,82,650</strong><span style={{fontSize:11,color:'hsl(var(--secondary))'}}>↑ 18.4% vs May</span></div><div className="metric"><small>Pieces in the edit</small><strong>128</strong><span style={{fontSize:11,color:'hsl(var(--muted-foreground))'}}>Across 5 collections</span></div><div className="metric"><small>Orders to pack</small><strong>24</strong><span style={{fontSize:11,color:'hsl(var(--primary))'}}>Today, before 4pm</span></div></div><div className="admin-table"><div style={{padding:20,display:'flex',justifyContent:'space-between'}}><h2 style={{font:'500 28px var(--app-font-serif)',margin:0}}>Recent inventory</h2><LayoutDashboard size={18}/></div><table><thead><tr><th>Product</th><th>Collection</th><th>Price</th><th>Stock</th><th>Status</th></tr></thead><tbody>{products.slice(0,7).map(p=><tr key={p.id}><td>{p.name}</td><td>{p.category}</td><td>{money(p.price)}</td><td>{[8,24,3,17,42,6,19][products.indexOf(p)]} units</td><td><span className="status">{p.badge==='New in'?'New':'Live'}</span></td></tr>)}</tbody></table></div></main>}

function Footer(){return <footer className="footer"><div className="footer-grid"><div><Link href="/" className="logo">style<span>h</span><i>u</i>b</Link><p>Thoughtfully edited fashion for every version of you. Designed in India, made for everywhere.</p></div><div><h4>Shop</h4><Link href="/category/women">Women</Link><Link href="/category/men">Men</Link><Link href="/category/girls">Girls</Link></div><div><h4>Help</h4><Link href="/account">Track order</Link><Link href="/cart">Shipping & returns</Link><Link href="/account">Contact us</Link></div><div><h4>Follow along</h4><a href="#journal">Instagram</a><a href="#journal">Pinterest</a><a href="#journal">The journal</a></div></div><div className="footline"><span>© 2025 StyleHub India</span><span>Made with care in New Delhi</span></div></footer>}

function App(){ const [wish,setWish]=useState<Product[]>([]); const [cart,setCart]=useState<CartItem[]>([]); const [search,setSearch]=useState(''); const [toast,setToast]=useState(''); const notify=(s:string)=>{setToast(s);setTimeout(()=>setToast(''),2300)}; const toggleWish=(p:Product)=>{setWish(w=>{const has=w.some(x=>x.id===p.id);notify(has?'Removed from wishlist':'Saved to wishlist');return has?w.filter(x=>x.id!==p.id):[...w,p]})}; const addCart=(p:Product,size='M')=>{setCart(c=>{const found=c.find(x=>x.product.id===p.id&&x.size===size);return found?c.map(x=>x===found?{...x,qty:x.qty+1}:x):[...c,{product:p,size,qty:1}]});notify(`${p.name} added to your bag`)}; const count=cart.reduce((a,x)=>a+x.qty,0);
  return <Shell cartCount={count} wishCount={wish.length} search={search} setSearch={setSearch}><Switch><Route path="/"><Home wish={wish} toggleWish={toggleWish} addCart={addCart}/></Route><Route path="/category/:category"><Catalog category={(useParams<{category:Category}>().category||'women') as Category} wish={wish} toggleWish={toggleWish} addCart={addCart} search={search}/></Route><Route path="/product/:id"><ProductDetail wish={wish} toggleWish={toggleWish} addCart={addCart}/></Route><Route path="/wishlist"><Wishlist wish={wish} toggleWish={toggleWish} addCart={addCart}/></Route><Route path="/cart"><Cart cart={cart} setCart={setCart}/></Route><Route path="/checkout"><Checkout cart={cart} onOrder={()=>{setCart([]);notify('Order placed successfully')}}/></Route><Route path="/account"><Account/></Route><Route path="/admin"><Admin/></Route><Route><NotFound/></Route></Switch>{toast&&<div className="toast" data-testid="status-toast">{toast}</div>}<Footer/></Shell>;
}
function NotFound(){return <main className="order-success"><span className="eyebrow">404 / Wrong turn</span><h1>That page wandered off.</h1><Link className="btn btn-dark" href="/" data-testid="link-not-found-home">Back to the edit</Link></main>}
export default App;